version: "2"
services:
  server:
    build: ./server
    ports:
      - 8002:8002
    depends_on:
      - db
  db:
    image: mysql:8.0.23
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: 'avilon'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro